apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    upstream go_backend {
        server monitor-service:8081; # 指向 K8s 内部的服务名
    }
    server {
        listen 8080;
        location / {
            proxy_pass http://go_backend;
        }
    }